### PR TITLE
Streamlined project templates

### PR DESCRIPTION
**Pull request by nsubtil**
Continuing from #12

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
Probably worth adding that the list is WIP and PRs to add more is encouraged. Other than that, looks fine to me.

**Comment by kvark** [comment]
Does license have to be explicitly mentioned here? Since most projects are on github, and it's platform recognizes the license natively, it's always one click away:
gh-license
:

**Comment by nsubtil** [comment]
I think having the license listed in the project map is useful --- it's an important consideration in some environments when deciding whether a project is usable.

**Comment by KarenGhavam-lunarG** [comment]
Looks good to me. Let's go ahead and merge this version and start adding projects to it.

**Pull request merged**
